use n42_legacy_codec::{deserialize, deserialize_from, serialize, serialize_into};
use n42_qmdb_state::forest::{ForestCheckpoint, ForestDelta};
use serde::{Deserialize, Serialize};

// These files were generated by unpatched registry bincode 1.3.3, not this codec.
const CHECKPOINT: &[u8] = include_bytes!("fixtures/forest-checkpoint-v1.bin");
const DELTA: &[u8] = include_bytes!("fixtures/forest-delta-v2.bin");

#[test]
fn reads_and_reproduces_existing_checkpoint_bytes() {
    let checkpoint: ForestCheckpoint = deserialize(CHECKPOINT).unwrap();
    assert_eq!(checkpoint.version, 1);
    assert_eq!(checkpoint.head_number, 42);
    assert_eq!(checkpoint.head_hash.as_slice(), &[0xab; 32]);
    assert_eq!(checkpoint.next_slot, 65);
    assert_eq!(checkpoint.active, vec![u64::MAX, 1]);
    assert_eq!(serialize(&checkpoint).unwrap(), CHECKPOINT);
}

#[test]
fn reads_and_reproduces_existing_delta_bytes() {
    let delta: ForestDelta = deserialize(DELTA).unwrap();
    assert_eq!(delta.version, 2);
    assert_eq!(delta.head_number, 43);
    assert_eq!(delta.head_hash.as_slice(), &[0xcd; 32]);
    assert_eq!(delta.base_next_slot, 65);
    assert_eq!(delta.next_slot, 67);
    assert!(delta.appended.is_empty());
    assert_eq!(delta.changed, vec![(0, false), (65, false), (66, true)]);
    assert_eq!(serialize(&delta).unwrap(), DELTA);
}

#[test]
fn consecutive_stream_records_do_not_consume_the_next_record() {
    let checkpoint: ForestCheckpoint = deserialize(CHECKPOINT).unwrap();
    let delta: ForestDelta = deserialize(DELTA).unwrap();
    let mut bytes = Vec::new();
    serialize_into(&mut bytes, &checkpoint).unwrap();
    serialize_into(&mut bytes, &delta).unwrap();
    assert_eq!(bytes, [CHECKPOINT, DELTA].concat());
    let mut reader = bytes.as_slice();
    let _: ForestCheckpoint = deserialize_from(&mut reader).unwrap();
    assert_eq!(reader, DELTA);
    let _: ForestDelta = deserialize_from(&mut reader).unwrap();
    assert!(reader.is_empty());
}

#[test]
fn preserves_free_function_trailing_bytes_and_rejects_truncation() {
    let bytes = [CHECKPOINT, &[0xff; 7]].concat();
    let _: ForestCheckpoint = deserialize(&bytes).unwrap();
    for end in 0..CHECKPOINT.len() {
        assert!(deserialize::<ForestCheckpoint>(&CHECKPOINT[..end]).is_err());
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
enum Choice {
    None,
    Some(u64),
    Pair(bool, String),
}

#[test]
fn enums_and_integer_widths_keep_the_legacy_format() {
    // bincode 1 uses u32 enum tags and fixed-width little-endian integers.
    assert_eq!(serialize(&Choice::None).unwrap(), 0u32.to_le_bytes());
    assert_eq!(
        serialize(&Choice::Some(u64::MAX)).unwrap(),
        [
            1u32.to_le_bytes().as_slice(),
            u64::MAX.to_le_bytes().as_slice()
        ]
        .concat()
    );
    let value = Choice::Pair(true, "你好".into());
    let expected = [
        2u32.to_le_bytes().as_slice(),
        &[1],
        6u64.to_le_bytes().as_slice(),
        "你好".as_bytes(),
    ]
    .concat();
    assert_eq!(serialize(&value).unwrap(), expected);
    assert_eq!(deserialize::<Choice>(&expected).unwrap(), value);
}

#[test]
fn validator_changes_keep_the_bytes_used_by_consensus_hashes() {
    use n42_h2_primitives::consensus::ValidatorChange;
    let bytes = include_bytes!("fixtures/validator-changes.bin");
    let changes: Vec<ValidatorChange> = deserialize(bytes).unwrap();
    assert_eq!(changes.len(), 2);
    match &changes[0] {
        ValidatorChange::Add {
            address,
            bls_public_key,
            p2p_peer_id,
        } => {
            assert_eq!(address.as_slice(), &[0x11; 20]);
            bls_public_key.validate().unwrap();
            assert_eq!(p2p_peer_id.as_deref(), Some("peer-1"));
        }
        _ => panic!("expected the original Add variant"),
    }
    match &changes[1] {
        ValidatorChange::Remove { address } => assert_eq!(address.as_slice(), &[0x22; 20]),
        _ => panic!("expected the original Remove variant"),
    }
    assert_eq!(serialize(&changes).unwrap().as_slice(), bytes);
    for end in 0..bytes.len() {
        assert!(deserialize::<Vec<ValidatorChange>>(&bytes[..end]).is_err());
    }
}
