// Copyright (c) 2017-2025 N42 Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

//! gov5-compatible gossip message IDs.
//!
//! gov5 computes `MsgID = Keccak256(genesisHash || topic || data)[..20]`
//! (`internal/p2p/message_id.go`). Two details are easy to get wrong:
//!
//! 1. **It is Keccak256, not SHA-256.** gov5's own doc comment on `MsgID` says
//!    SHA256, but `common/hash.Hash` pulls a `crypto.KeccakState` from its
//!    pool. The vectors in `testdata/gov5_message_id_v1.json` were generated by
//!    calling that same Go function, so they settle it.
//! 2. **The topic is folded in, and before the data.** go-libp2p-pubsub marks a
//!    message ID seen globally across every topic and *before* validation, so a
//!    bare `hash(data)` would let an attacker replay a block's bytes on any
//!    other subscribed topic to pre-seed the seen-cache and have the genuine
//!    block dropped as a duplicate. Folding in the topic and the fork-scoping
//!    genesis hash makes identical bytes on different topics distinct IDs.
//!
//! The message ID is a purely local dedup key, so a node computing it
//! differently still interoperates — it just dedups differently. Matching gov5
//! keeps duplicate suppression identical across a mixed Rust/Go fleet.
//!
//! N42-26 uses a different function here (`keccak256(data || topic)`, no
//! genesis hash). This crate deliberately implements gov5's.

use alloy_primitives::{keccak256, B256};
use libp2p::gossipsub::{Message, MessageId};

/// Length of a gov5 message ID in bytes.
pub const MESSAGE_ID_LEN: usize = 20;

/// Computes gov5's `MsgID` over explicit parts.
pub fn gov5_message_id_parts(genesis_hash: B256, topic: &str, data: &[u8]) -> [u8; MESSAGE_ID_LEN] {
    let mut combined = Vec::with_capacity(B256::len_bytes() + topic.len() + data.len());
    combined.extend_from_slice(genesis_hash.as_slice());
    combined.extend_from_slice(topic.as_bytes());
    combined.extend_from_slice(data);
    let digest = keccak256(&combined);
    let mut out = [0u8; MESSAGE_ID_LEN];
    out.copy_from_slice(&digest[..MESSAGE_ID_LEN]);
    out
}

/// Builds the `message_id_fn` gossipsub expects, bound to a genesis hash.
pub fn gov5_message_id_fn(genesis_hash: B256) -> impl Fn(&Message) -> MessageId + Send + Sync + 'static {
    move |message: &Message| {
        MessageId::from(
            gov5_message_id_parts(genesis_hash, message.topic.as_str(), &message.data).to_vec(),
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde::Deserialize;

    #[derive(Deserialize)]
    struct Vector {
        genesis_hash: String,
        topic: String,
        data: String,
        message_id: String,
    }

    #[derive(Deserialize)]
    struct Vectors {
        vectors: Vec<Vector>,
    }

    /// Cross-client: every vector was produced by gov5's own `common/hash.Hash`
    /// through the exact byte layout of `internal/p2p.MsgID`.
    #[test]
    fn matches_gov5_message_id_vectors() {
        let doc: Vectors =
            serde_json::from_str(include_str!("../testdata/gov5_message_id_v1.json")).unwrap();
        assert_eq!(doc.vectors.len(), 5, "fixture lost vectors");

        for (i, v) in doc.vectors.iter().enumerate() {
            let genesis = B256::from_slice(&hex::decode(&v.genesis_hash).unwrap());
            let data = hex::decode(&v.data).unwrap();
            let got = gov5_message_id_parts(genesis, &v.topic, &data);
            assert_eq!(
                hex::encode(got),
                v.message_id,
                "vector {i} (topic {}) diverged from gov5",
                v.topic
            );
        }
    }

    /// The same bytes on a different topic must produce a different ID — this is
    /// the property that defeats cross-topic seen-cache poisoning. Vectors 2 and
    /// 3 in the fixture are exactly this pair.
    #[test]
    fn topic_scoping_separates_identical_payloads() {
        let doc: Vectors =
            serde_json::from_str(include_str!("../testdata/gov5_message_id_v1.json")).unwrap();
        let suffixed = &doc.vectors[2];
        let bare = &doc.vectors[3];
        assert_eq!(suffixed.data, bare.data);
        assert_eq!(suffixed.genesis_hash, bare.genesis_hash);
        assert_ne!(suffixed.topic, bare.topic);
        assert_ne!(suffixed.message_id, bare.message_id);
    }

    /// Genesis scoping: the same bytes on the same topic but a different chain
    /// must not collide either.
    #[test]
    fn genesis_scoping_separates_chains() {
        let data = b"identical";
        let a = gov5_message_id_parts(B256::repeat_byte(0xaa), super::super::topic::H2_V4_TOPIC, data);
        let b = gov5_message_id_parts(B256::repeat_byte(0xbb), super::super::topic::H2_V4_TOPIC, data);
        assert_ne!(a, b);
    }

    #[test]
    fn is_keccak_not_sha256() {
        // Guards the documented gov5 comment/implementation mismatch: if someone
        // "fixes" this to SHA-256 per the comment, the fixture test above fails
        // and this one names why.
        let empty = gov5_message_id_parts(B256::ZERO, "/n42/h2/4/ssz_snappy", &[]);
        let expected = keccak256(
            [B256::ZERO.as_slice(), b"/n42/h2/4/ssz_snappy".as_slice()].concat(),
        );
        assert_eq!(empty, expected[..MESSAGE_ID_LEN]);
    }
}
