// Copyright (c) 2017-2025 N42 Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

//! gov5's `/rpc/status/1/ssz_snappy` message and wire framing.
//!
//! gov5 requires this handshake to keep a connection: `internal/sync/service.go`
//! registers `AddConnectionHandler(s.reValidatePeer, s.sendGoodbye)`, so a peer
//! that cannot answer a status request is sent goodbye and dropped a few seconds
//! after connecting. An observer that only speaks gossip therefore never stays
//! attached long enough to receive anything.
//!
//! # Wire format
//!
//! Request:  `varint(len(ssz))` ++ snappy-**framed**(ssz)
//! Response: `0x00` (success) ++ the same framing
//!
//! The varint length is of the *uncompressed* SSZ, and the compression is the
//! snappy **framing** format (`snappy.NewBufferedWriter` in Go,
//! [`snap::write::FrameEncoder`] here), not the raw block format that the gossip
//! path uses. Mixing the two is the easiest mistake to make: gossip payloads are
//! raw-snappy, RPC payloads are framed-snappy.
//!
//! # SSZ layout
//!
//! Despite `sync_pb.Status` carrying eight protobuf fields, gov5's SSZ codegen
//! (`proto/sync_pb/generated.ssz.go`) serialises exactly two, both as
//! variable-length `H256`:
//!
//! ```text
//! [0..4]   offset of genesis_hash  = 8   (u32 LE)
//! [4..8]   offset of current_height = 40 (u32 LE)
//! [8..40]  genesis_hash   as H256
//! [40..72] current_height as H256
//! ```
//!
//! An `H256` is four `u64`s — `Hi.Hi, Hi.Lo, Lo.Hi, Lo.Lo` — each read from the
//! 32-byte value **big-endian** (`common/utils.ConvertHashToH256`) and then
//! written **little-endian** by SSZ. The net effect is that each 8-byte group of
//! the hash appears byte-reversed on the wire. `testdata/gov5_status_v1.json`
//! pins this against vectors generated by gov5's own codegen.

use alloy_primitives::B256;

/// gov5's libp2p protocol id for the status handshake.
pub const STATUS_PROTOCOL: &str = "/rpc/status/1/ssz_snappy";

/// `responseCodeSuccess` in `internal/sync`.
pub const RESPONSE_CODE_SUCCESS: u8 = 0;

/// Encoded size of an SSZ `Status`: 8 bytes of offsets plus two `H256`s.
pub const STATUS_SSZ_LEN: usize = 8 + 32 + 32;

/// `MaxChunkSize` in `internal/p2p/encoder` — the cap gov5 applies to ordinary
/// RPC chunks. Anything claiming more is refused before allocating.
pub const MAX_CHUNK_SIZE: u64 = 1 << 20;

/// A gov5 status message.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Status {
    /// The peer's genesis hash. gov5 derives its fork digest from the first four
    /// bytes of this (`common/utils.CreateForkDigest`) and disconnects on
    /// mismatch, so it is the field that decides whether a connection survives.
    pub genesis_hash: B256,
    /// Current head height, as a 256-bit value.
    pub current_height: B256,
}

impl Status {
    /// Builds a status for a chain at `height`.
    pub fn new(genesis_hash: B256, height: u64) -> Self {
        Self { genesis_hash, current_height: B256::from(alloy_primitives::U256::from(height)) }
    }

    /// The head height, saturating if the peer reports something past `u64`.
    pub fn height(&self) -> u64 {
        let bytes = self.current_height.as_slice();
        if bytes[..24].iter().any(|b| *b != 0) {
            return u64::MAX;
        }
        u64::from_be_bytes(bytes[24..32].try_into().expect("8 bytes"))
    }

    /// The four-byte fork digest gov5 compares against its own.
    pub fn fork_digest(&self) -> [u8; 4] {
        self.genesis_hash.as_slice()[..4].try_into().expect("4 bytes")
    }

    /// Serialises to gov5's SSZ form.
    pub fn to_ssz(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(STATUS_SSZ_LEN);
        out.extend_from_slice(&8u32.to_le_bytes());
        out.extend_from_slice(&40u32.to_le_bytes());
        out.extend_from_slice(&encode_h256(&self.genesis_hash));
        out.extend_from_slice(&encode_h256(&self.current_height));
        out
    }

    /// Parses gov5's SSZ form.
    pub fn from_ssz(bytes: &[u8]) -> Result<Self, StatusError> {
        if bytes.len() != STATUS_SSZ_LEN {
            return Err(StatusError::Length { got: bytes.len(), want: STATUS_SSZ_LEN });
        }
        let off0 = u32::from_le_bytes(bytes[0..4].try_into().expect("4 bytes"));
        let off1 = u32::from_le_bytes(bytes[4..8].try_into().expect("4 bytes"));
        if off0 != 8 || off1 != 40 {
            return Err(StatusError::Offsets { got: (off0, off1) });
        }
        Ok(Self {
            genesis_hash: decode_h256(&bytes[8..40]),
            current_height: decode_h256(&bytes[40..72]),
        })
    }
}

/// Each 8-byte group is read big-endian into a `u64`, then written little-endian
/// by SSZ — which is a byte reversal per group.
fn encode_h256(value: &B256) -> [u8; 32] {
    let mut out = [0u8; 32];
    for group in 0..4 {
        let src = &value.as_slice()[group * 8..group * 8 + 8];
        let word = u64::from_be_bytes(src.try_into().expect("8 bytes"));
        out[group * 8..group * 8 + 8].copy_from_slice(&word.to_le_bytes());
    }
    out
}

fn decode_h256(bytes: &[u8]) -> B256 {
    let mut out = [0u8; 32];
    for group in 0..4 {
        let word = u64::from_le_bytes(
            bytes[group * 8..group * 8 + 8].try_into().expect("8 bytes"),
        );
        out[group * 8..group * 8 + 8].copy_from_slice(&word.to_be_bytes());
    }
    B256::from(out)
}

/// Failures decoding a status message or its framing.
#[derive(Debug, thiserror::Error)]
pub enum StatusError {
    /// SSZ payload was not the expected length.
    #[error("status ssz is {got} bytes, expected {want}")]
    Length {
        /// Bytes received.
        got: usize,
        /// Bytes expected.
        want: usize,
    },
    /// The two SSZ offsets were not the fixed values gov5 writes.
    #[error("status ssz offsets {got:?}, expected (8, 40)")]
    Offsets {
        /// The offsets read.
        got: (u32, u32),
    },
    /// The declared uncompressed length exceeded gov5's chunk cap.
    #[error("declared length {got} exceeds max chunk size {MAX_CHUNK_SIZE}")]
    TooLong {
        /// The declared length.
        got: u64,
    },
    /// The varint length prefix was malformed.
    #[error("malformed varint length prefix")]
    Varint,
    /// Snappy framing was malformed.
    #[error("snappy framing: {0}")]
    Snappy(String),
    /// The peer answered with a non-success response code.
    #[error("peer returned response code {0}")]
    ResponseCode(u8),
}

/// Encodes a varint, matching Go's `binary.PutUvarint`.
pub fn encode_varint(mut value: u64) -> Vec<u8> {
    let mut out = Vec::with_capacity(10);
    while value >= 0x80 {
        out.push((value as u8) | 0x80);
        value >>= 7;
    }
    out.push(value as u8);
    out
}

/// Decodes a varint, returning the value and how many bytes it consumed.
pub fn decode_varint(bytes: &[u8]) -> Result<(u64, usize), StatusError> {
    let mut value = 0u64;
    let mut shift = 0u32;
    for (i, byte) in bytes.iter().take(10).enumerate() {
        value |= u64::from(byte & 0x7f)
            .checked_shl(shift)
            .ok_or(StatusError::Varint)?;
        if byte & 0x80 == 0 {
            return Ok((value, i + 1));
        }
        shift += 7;
    }
    Err(StatusError::Varint)
}

/// Frames a payload the way gov5's `EncodeWithMaxLength` does.
pub fn frame_payload(ssz: &[u8]) -> Result<Vec<u8>, StatusError> {
    use std::io::Write;
    let mut out = encode_varint(ssz.len() as u64);
    let mut encoder = snap::write::FrameEncoder::new(Vec::new());
    encoder
        .write_all(ssz)
        .map_err(|e| StatusError::Snappy(e.to_string()))?;
    let compressed = encoder
        .into_inner()
        .map_err(|e| StatusError::Snappy(e.to_string()))?;
    out.extend_from_slice(&compressed);
    Ok(out)
}

/// Decodes a framed payload produced by [`frame_payload`].
pub fn unframe_payload(bytes: &[u8]) -> Result<Vec<u8>, StatusError> {
    use std::io::Read;
    let (len, consumed) = decode_varint(bytes)?;
    if len > MAX_CHUNK_SIZE {
        return Err(StatusError::TooLong { got: len });
    }
    let mut out = vec![0u8; len as usize];
    let mut decoder = snap::read::FrameDecoder::new(&bytes[consumed..]);
    decoder
        .read_exact(&mut out)
        .map_err(|e| StatusError::Snappy(e.to_string()))?;
    Ok(out)
}

/// Walks snappy frame headers to find where a framed payload ends.
///
/// Needed because the varint declares the *uncompressed* length, which says
/// nothing about how many bytes to read off the wire. gov5's Go decoder sidesteps
/// this by reading through a streaming reader; reading to EOF instead would
/// depend on the peer half-closing, which is not guaranteed. Parsing the frame
/// headers — 1 byte of type, 3 bytes of little-endian length — needs no
/// decompression and no CRC check, and gives an exact boundary.
///
/// Returns `Ok(None)` when more bytes are needed.
pub fn framed_len(bytes: &[u8]) -> Result<Option<usize>, StatusError> {
    let (declared, consumed) = match decode_varint(bytes) {
        Ok(v) => v,
        Err(_) if bytes.len() < 10 => return Ok(None),
        Err(e) => return Err(e),
    };
    if declared > MAX_CHUNK_SIZE {
        return Err(StatusError::TooLong { got: declared });
    }

    let mut cursor = consumed;
    let mut produced = 0u64;
    while produced < declared {
        if cursor + 4 > bytes.len() {
            return Ok(None);
        }
        let chunk_type = bytes[cursor];
        let chunk_len = u32::from_le_bytes([bytes[cursor + 1], bytes[cursor + 2], bytes[cursor + 3], 0])
            as usize;
        let body_start = cursor + 4;
        let body_end = body_start + chunk_len;
        if body_end > bytes.len() {
            return Ok(None);
        }
        match chunk_type {
            // Stream identifier: contributes nothing.
            0xff => {}
            // Compressed: 4-byte CRC then a raw snappy block.
            0x00 => {
                let block = &bytes[body_start + 4..body_end];
                produced += snap::raw::decompress_len(block)
                    .map_err(|e| StatusError::Snappy(e.to_string()))?
                    as u64;
            }
            // Uncompressed: 4-byte CRC then the bytes themselves.
            0x01 => produced += (chunk_len - 4) as u64,
            // Reserved-skippable.
            0x80..=0xfe => {}
            other => return Err(StatusError::Snappy(format!("reserved chunk type {other:#x}"))),
        }
        cursor = body_end;
    }
    Ok(Some(cursor))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde::Deserialize;

    #[derive(Deserialize)]
    struct Vector {
        genesis_hash: String,
        height: u64,
        ssz_hex: String,
        request_hex: String,
        response_hex: String,
    }

    #[derive(Deserialize)]
    struct Vectors {
        protocol: String,
        vectors: Vec<Vector>,
    }

    fn vectors() -> Vectors {
        serde_json::from_str(include_str!("../testdata/gov5_status_v1.json")).unwrap()
    }

    #[test]
    fn protocol_id_matches_gov5() {
        // gov5: protocolPrefix "/rpc" + "/status" + SchemaVersionV1 "/1"
        // + encoder.ProtocolSuffix() "/ssz_snappy".
        assert_eq!(STATUS_PROTOCOL, "/rpc/status/1/ssz_snappy");
        assert_eq!(vectors().protocol, STATUS_PROTOCOL);
    }

    #[test]
    fn ssz_matches_gov5_codegen() {
        for v in vectors().vectors {
            let status = Status::new(v.genesis_hash.parse().unwrap(), v.height);
            assert_eq!(
                hex::encode(status.to_ssz()),
                v.ssz_hex,
                "ssz diverged for height {}",
                v.height
            );
        }
    }

    #[test]
    fn ssz_roundtrips_through_gov5_bytes() {
        for v in vectors().vectors {
            let decoded = Status::from_ssz(&hex::decode(&v.ssz_hex).unwrap()).unwrap();
            assert_eq!(decoded.genesis_hash, v.genesis_hash.parse::<B256>().unwrap());
            assert_eq!(decoded.height(), v.height);
            assert_eq!(hex::encode(decoded.to_ssz()), v.ssz_hex);
        }
    }

    #[test]
    fn request_framing_matches_gov5() {
        for v in vectors().vectors {
            let status = Status::new(v.genesis_hash.parse().unwrap(), v.height);
            assert_eq!(
                hex::encode(frame_payload(&status.to_ssz()).unwrap()),
                v.request_hex,
                "request framing diverged for height {}",
                v.height
            );
        }
    }

    #[test]
    fn response_is_the_success_byte_then_the_request_framing() {
        for v in vectors().vectors {
            let status = Status::new(v.genesis_hash.parse().unwrap(), v.height);
            let mut resp = vec![RESPONSE_CODE_SUCCESS];
            resp.extend_from_slice(&frame_payload(&status.to_ssz()).unwrap());
            assert_eq!(hex::encode(resp), v.response_hex);
        }
    }

    #[test]
    fn unframes_gov5_bytes_back_to_ssz() {
        for v in vectors().vectors {
            let ssz = unframe_payload(&hex::decode(&v.request_hex).unwrap()).unwrap();
            assert_eq!(hex::encode(&ssz), v.ssz_hex);
        }
    }

    #[test]
    fn framed_len_finds_the_exact_boundary() {
        for v in vectors().vectors {
            let bytes = hex::decode(&v.request_hex).unwrap();
            assert_eq!(framed_len(&bytes).unwrap(), Some(bytes.len()));
            // A trailing byte must not extend the reported boundary — otherwise a
            // second message on the same stream would be swallowed.
            let mut extended = bytes.clone();
            extended.push(0xaa);
            assert_eq!(framed_len(&extended).unwrap(), Some(bytes.len()));
            // Truncation must report "need more", never a wrong boundary.
            for cut in 1..bytes.len() {
                assert_eq!(framed_len(&bytes[..cut]).unwrap_or(None), None, "cut at {cut}");
            }
        }
    }

    #[test]
    fn fork_digest_is_the_first_four_genesis_bytes() {
        // gov5 utils.CreateForkDigest ignores the height and returns
        // ToBytes4(genesisHash).
        let status = Status::new(
            "3bec3e862313f3f4f21a3f222fd90921cc01d246edcf19c52fd5c4e43f5c7a99".parse().unwrap(),
            7,
        );
        assert_eq!(status.fork_digest(), [0x3b, 0xec, 0x3e, 0x86]);
    }

    #[test]
    fn oversized_declarations_are_refused_before_allocating() {
        let mut bytes = encode_varint(MAX_CHUNK_SIZE + 1);
        bytes.extend_from_slice(&[0u8; 8]);
        assert!(matches!(unframe_payload(&bytes), Err(StatusError::TooLong { .. })));
        assert!(matches!(framed_len(&bytes), Err(StatusError::TooLong { .. })));
    }

    #[test]
    fn varint_matches_go_put_uvarint() {
        for (value, expected) in [
            (0u64, vec![0x00]),
            (1, vec![0x01]),
            (127, vec![0x7f]),
            (128, vec![0x80, 0x01]),
            (300, vec![0xac, 0x02]),
            (72, vec![0x48]),
            (u64::MAX, vec![0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01]),
        ] {
            assert_eq!(encode_varint(value), expected, "encoding {value}");
            assert_eq!(decode_varint(&expected).unwrap(), (value, expected.len()));
        }
    }
}
