[package]
name = "merkle_db_rs"
version = "0.1.0"
edition = "2024"

[features]
debug = []

[dependencies]
serde_json.workspace = true
reth-codecs.workspace = true
bytes.workspace = true
ethereum_ssz.workspace = true
ethereum_ssz_derive.workspace = true
serde.workspace = true
sha2 = "0.10.9"
tree_hash.workspace = true
typenum = "1.19.0"
