use reth_metrics::{
    metrics::{Counter, Gauge, Histogram},
    Metrics,
};

#[derive(Metrics)]
#[metrics(scope = "consensus.client")]
pub(crate) struct MinerMetrics {
    /// How many verifications were submitted.
    pub(crate) num_verification_submission: Counter,
    /// How many block hash mismatches happened.
    pub(crate) num_verification_block_hash_mismatch: Counter,
    /// How many attestations are in blocks generated by this node
    pub(crate) num_attestations_in_blocks_generated_by_this_node: Counter,

    /// num_order_in_round
    pub(crate) num_order_in_round: Counter,
    /// num_out_of_order_in_round
    pub(crate) num_out_of_order_in_round: Counter,

    /// num_generated_blocks
    pub(crate) num_generated_blocks: Counter,
    /// num_skipped_new_block
    pub(crate) num_skipped_new_block: Counter,
    /// num_should_skip_block_generation
    pub(crate) num_should_skip_block_generation: Counter,
    /// num_long_delayed_blocks
    pub(crate) num_long_delayed_blocks: Counter,
    /// num_fetched_blocks
    pub(crate) num_fetched_blocks: Counter,
}
