use reth_metrics::{
    metrics::{Counter, Gauge, Histogram},
    Metrics,
};

#[derive(Metrics)]
#[metrics(scope = "consensus.client")]
pub(crate) struct MinerMetrics {
    /// How many verifications were submitted.
    pub(crate) num_verification_submission: Counter,
    /// How many block hash mismatches happpened.
    pub(crate) num_verification_block_hash_mismatch: Counter,
    /// How many attestations are in blocks generated by this node
    pub(crate) num_attestations_in_blocks_generated_by_this_node: Counter,
}
