name: Clippy

on:
  push:
    branches: [ "main" ] # Or any other branches you want to lint
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run Clippy
        #run: cargo clippy --workspace --all-targets -- -D warnings
        run: cargo clippy --workspace --lib --bins --all-features
